server:
  servlet:
    context-path: /test
  port: 8080
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: passw0rd
    driver-class-name: org.postgresql.Driver

mybatis:
  type-aliases-package: com.banmajio.bean
  mapper-locations: classpath:mapper/*.xml